# Generated by Django 6.0.7 on 2026-07-21 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_load_harbor_pine_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='website', max_length=30)),
                ('privacy_acknowledged', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('in_progress', 'In progress'), ('resolved', 'Resolved'), ('handoff', 'Human handoff'), ('fallback', 'Fallback'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('resolution_path', models.CharField(choices=[('none', 'Not resolved'), ('faq', 'FAQ'), ('product', 'Product'), ('document', 'Document'), ('order', 'Order'), ('lead', 'Lead'), ('handoff', 'Human handoff'), ('fallback', 'Fallback')], db_index=True, default='none', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('detected_intent', models.CharField(blank=True, choices=[('greeting', 'Greeting'), ('faq', 'FAQ'), ('product', 'Product'), ('document', 'Document'), ('order', 'Order'), ('lead', 'Lead'), ('handoff', 'Human handoff'), ('unsupported', 'Unsupported')], db_index=True, max_length=20)),
                ('resolution_path', models.CharField(choices=[('none', 'Not resolved'), ('faq', 'FAQ'), ('product', 'Product'), ('document', 'Document'), ('order', 'Order'), ('lead', 'Lead'), ('handoff', 'Human handoff'), ('fallback', 'Fallback')], default='none', max_length=20)),
                ('source_references', models.JSONField(blank=True, default=list)),
                ('decision_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_chat.chatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('normalized_topic', models.CharField(db_index=True, max_length=200)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('converted', 'Converted to FAQ'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('converted_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_unanswered_questions', to='knowledge.faq')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unanswered_questions', to='support_chat.chatsession')),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_seen_at'],
            },
        ),
    ]
