# Generated by Django 6.0.7 on 2026-07-20 19:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=30, unique=True)),
                ('product_name', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(choices=[('Home Organization', 'Home Organization'), ('Kitchen', 'Kitchen'), ('Bath', 'Bath'), ('Office', 'Office'), ('Outdoor', 'Outdoor')], db_index=True, max_length=40)),
                ('short_description', models.TextField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued')], db_index=True, max_length=20)),
                ('stock_band', models.CharField(choices=[('healthy', 'Healthy'), ('moderate', 'Moderate'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued')], max_length=20)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('care_instructions', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True, max_length=300)),
                ('last_updated', models.DateField()),
                ('data_owner', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sku'],
                'indexes': [models.Index(fields=['category', 'status'], name='catalog_cat_status_idx')],
            },
        ),
    ]
