# Generated by Django 6.0.7 on 2026-07-21 20:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('billing_zip', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, max_length=30)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('tracking_reference', models.CharField(blank=True, max_length=100)),
                ('eta_window', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('order_total_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_id'],
                'indexes': [models.Index(fields=['status', 'order_date'], name='orders_status_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderLookupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_order_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('outcome', models.CharField(choices=[('verified', 'Verified'), ('not_found', 'Order not found'), ('zip_mismatch', 'Billing ZIP mismatch'), ('missing_data', 'Missing verification data'), ('blocked', 'Blocked after repeated failures')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookup_attempts', to='orders.mockorder')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lookup_attempts', to='support_chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
