# Generated by Django 6.0.7 on 2026-07-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(choices=[('human_request', 'Customer requested a person'), ('unsupported', 'Unsupported or uncertain request'), ('complaint', 'Complaint or angry customer'), ('payment_refund', 'Payment or refund dispute'), ('safety_legal', 'Safety, injury, or legal concern'), ('privacy_request', 'Privacy or data request'), ('high_value_sales', 'High-value sales inquiry'), ('other', 'Other')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('reason', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('waiting_for_customer', 'Waiting for customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=30)),
                ('assigned_owner', models.CharField(blank=True, db_index=True, default='Support Queue', max_length=120)),
                ('sla_due_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_requests', to='support_chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['priority', 'status'], name='crm_hand_pri_stat_idx'), models.Index(fields=['assigned_owner', 'status'], name='crm_hand_owner_stat_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('inquiry_type', models.CharField(choices=[('product_advice', 'Product advice'), ('bulk_order', 'Bulk order'), ('trade_program', 'Trade program'), ('partnership', 'Partnership'), ('other', 'Other')], db_index=True, max_length=30)),
                ('product_sku', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(max_length=2000)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('owner', models.CharField(blank=True, db_index=True, default='Support Queue', max_length=120)),
                ('duplicate_review_required', models.BooleanField(db_index=True, default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='support_chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inquiry_type', 'status'], name='crm_lead_type_stat_idx'), models.Index(fields=['owner', 'status'], name='crm_lead_owner_stat_idx')],
            },
        ),
    ]
